# @package _global_

runtime:
  common:
    model_profile: r18
    output_dir: output
    device: cuda
    batch_size: 1
    num_workers: 2
    use_gpu: true
    use_xpu: false
    use_mlu: false
    use_npu: false
    log_iter: 20
    snapshot_epoch: 1
    print_flops: false
    print_params: false
    epoches: 120

  visualization:
    num_samples: 16
    tensorboard:
      enabled: false
      log_dir: runs/visualization
    wandb:
      enabled: false
      wandb_dir: wandb
      entity: null

  data_preparation:
    prepare_data: false
    supervisely_dataset_root: null
    supervisely_splits: [train, valid]
    ann_subdir: ann
    img_subdir: img
    wandb_project: null
    wandb_run_name: null

  export:
    post_process: true
    nms: true
    benchmark: false
    fuse_conv_bn: false

  actions:
    train: {}
    eval: {}
    inference: {}
    inference_onnx: {}
    export_onnx: {}
    export_coco_rle: {}
