services:
  runner:
    container_name: nn-framework-rtdetrv2-model-u20-cu128
    env_file:
      - ${PWD}/infra/adapter/rtdetrv2_pytorch/docker/.env
    working_dir: /workspace
    stdin_open: true
    tty: true
    build:
      context: ${PWD}
      dockerfile: infra/adapter/rtdetrv2_pytorch/docker/Dockerfile
      network: host
      args:
        BASE_IMAGE: nn-framework-runner:u20-cu128
    image: rtdetrv2-model:u20-cu128

    volumes:
      - ${PWD}:/workspace:rw
      - ${PWD}/docker/scripts:/workspace/scripts:rw
      - ${PWD}/infra/adapter/rtdetrv2_pytorch/experiments:/workspace/experiments:rw
      - ${HOME}/repo/datasets:/root/repo/datasets:rw
      - ${HOME}/.cache/torch:/root/.cache/torch:rw
