# @package _global_

runtime:
  use_gpu: true
  use_xpu: false
  use_mlu: false
  use_npu: false
  log_iter: 20
  save_dir: output
  snapshot_epoch: 1
  print_flops: false
  print_params: false
  epoches: 120
  
  export:
    post_process: true
    nms: true
    benchmark: false
    fuse_conv_bn: false

  prepare_data: false
  supervisely_dataset_root: null
  supervisely_splits: [train, valid]
  ann_subdir: ann
  img_subdir: img
  wandb_project: null
  wandb_run_name: null
