logging:
  level_colors:
    TRACE: "<white>"
    DEBUG: "<white>"
    INFO: "<white>"
    WARNING: "<yellow>"
    ERROR: "<red>"
    CRITICAL: "<RED><white>"

  console:
    enabled: true
    level: "INFO"

  file:
    enabled: true
    level: "INFO"
    path: "logs/{time:YYYY-MM-DD__HH-mm-ss}.log"
    rotation: "10 MB"
    retention: "1 week"
