services:
  runner:
    container_name: nn-framework-rtdetrv2-model
    env_file:
      - compose/.env.rtdetrv2
    build:
      context: ..
      dockerfile: infra/engine/model/wrappers/adapter/rtdetrv2_pytorch/Dockerfile
    image: rtdetrv2-model:local

