services:
  runner:
    container_name: nn-framework-rf-detr-model
    env_file:
      - compose/.env.rf-detr
    build:
      context: ..
      dockerfile: infra/engine/model/wrappers/adapter/rf_detr/Dockerfile
    image: rf-detr-model:local
